### PR TITLE
fix: request to https if the tls is enabled

### PR DESCRIPTION
**Pull request by Sanket-0510**
fixes: #437  if TLS is enabled all requests are directed to the HTTPS.

### CODE REVIEW

**Comment by dzikowski** [comment]
Thanks @Sanket-0510, I've approved the CI run. If CI tests fail, it means you need to also update snapshots. Just run locally:

```
npm run test:e2e-update
```

And commit changes. Fablo doesn't have local dev docs with that information yet (sorry for that). We have an issue to handle that: https://github.com/hyperledger-labs/fablo/issues/436.

**Comment by Sanket-0510** [comment]
> Thanks @Sanket-0510, I've approved the CI run. If CI tests fail, it means you need to also update snapshots. Just run locally:
> 
> ```
> npm run test:e2e-update
> ```
> 
> And commit changes. Fablo doesn't have local dev docs with that information yet (sorry for that). We have an issue to handle that: https://github.com/hyperledger-labs/fablo/issues/436.

Is this fine now?

**Comment by dzikowski** [comment]
Let's see if CI passes. Also the DCO check fails, what means, because all commits needs to contain DCO sign-off: https://wiki.linuxfoundation.org/dco

You need to either squash or update commits, and then force push.

**Comment by Sanket-0510** [comment]
> Let's see if CI passes. Also the DCO check fails, because all commits needs to contain DCO sign-off: https://wiki.linuxfoundation.org/dco
> 
> You need to either squash or update commits, and then force push.

I squashed the commit, and have signed it. Also I have run the e2e test command, tests pass successfully

**Comment by Sanket-0510** [comment]
Hey @dzikowski any idea why the tests are failing cause I guess I have done the changes at correct location, also I've ran e2e test also, nothing is failing locally!

**Comment by dzikowski** [comment]
test-k8 fails, because those are still in progress: https://github.com/hyperledger-labs/fablo/pull/425 and https://github.com/hyperledger-labs/fablo/pull/431

test-03-private-data fails, because it's a bit outdated, and we eventually want to remove this check: https://github.com/hyperledger-labs/fablo/issues/396

test-04-snapshot should be fixed on main branch now, once you merge, it should pass

**Comment by Sanket-0510** [comment]
> test-k8 fails, because those are still in progress: #425 and #431
> 
> test-03-private-data fails, because it's a bit outdated, and we eventually want to remove this check: #396
> 
> test-04-snapshot should be fixed on main branch now, once you merge, it should pass

I have rebased my dev branch with fablo's main updated branch, I hope this will solve the problem

**Review by dzikowski — APPROVED** [review]

**Pull request merged**
